defaults:
  - base_view_sampler

min_distance_between_context_views: 30
max_distance_between_context_views: 50
min_distance_to_context_views: 0
initial_min_distance_between_context_views: 20
initial_max_distance_between_context_views: 40
